default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: astronauts_development
test:
  adapter: postgresql
  encoding: utf8
  database: astronauts_test
  pool: 5
production:
  adapter: postgresql
  encoding: utf8
  database: astronauts_production
  pool: 5
staging:
  adapter: postgresql
  encoding: utf8
  database: astronauts_staging
  pool: 5